import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { supabase } from "../lib/supabase";

export type CloudProfile = { id: string; full_name: string; role: "student" | "teacher"; daily_goal: number };
export type SimpleResult = { cpm: number; accuracy: number; seconds: number; date: string };
type SchoolClass = { id: string; name: string; join_code: string; teacher_id: string };
type Assignment = { id: string; title: string; lesson_id: number; due_at: string | null };

export function AccountPage({ user, profile, results, completedCount, onProfile, onSignOut, onLesson }:{user:User;profile:CloudProfile;results:SimpleResult[];completedCount:number;onProfile:(p:CloudProfile)=>void;onSignOut:()=>void;onLesson:(id:number)=>void}) {
  const [tab,setTab]=useState<"profile"|"school">("profile");
  const [name,setName]=useState(profile.full_name),[goal,setGoal]=useState(profile.daily_goal),[saving,setSaving]=useState(false);
  const best=results.length?Math.max(...results.map(r=>r.cpm)):0, avg=results.length?Math.round(results.reduce((s,r)=>s+r.accuracy,0)/results.length):0;
  const todaySeconds=results.filter(r=>new Date(r.date).toDateString()===new Date().toDateString()).reduce((s,r)=>s+r.seconds,0), goalPercent=Math.min(100,Math.round(todaySeconds/60/goal*100));
  const save=async()=>{if(!supabase)return;setSaving(true);const {data}=await supabase.from("profiles").update({full_name:name,daily_goal:goal,updated_at:new Date().toISOString()}).eq("id",user.id).select().single();setSaving(false);if(data)onProfile(data as CloudProfile)};
  const becomeTeacher=async()=>{if(!supabase)return;const {data}=await supabase.from("profiles").update({role:"teacher"}).eq("id",user.id).select().single();if(data)onProfile(data as CloudProfile);setTab("school")};
  return <section className="account-page page-width"><div className="account-hero"><div className="avatar">{profile.full_name?.[0]?.toUpperCase()||"Q"}</div><div><p className="eyebrow">ЖЕКЕ КАБИНЕТ</p><h1>{profile.full_name || "QazaqType қолданушысы"}</h1><span>{user.email} · {profile.role === "teacher" ? "Мұғалім" : "Оқушы"}</span></div><button onClick={onSignOut}>Шығу</button></div>
    <div className="account-tabs"><button className={tab==="profile"?"selected":""} onClick={()=>setTab("profile")}>Профиль және мақсат</button><button className={tab==="school"?"selected":""} onClick={()=>setTab("school")}>{profile.role==="teacher"?"Мұғалім кабинеті":"Менің сыныбым"}</button></div>
    {tab==="profile"?<div className="profile-layout"><section className="profile-main"><h2>Жеке мәліметтер</h2><label>Аты-жөні<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Күнделікті мақсат<select value={goal} onChange={e=>setGoal(Number(e.target.value))}>{[5,10,15,20,30,45,60].map(v=><option value={v} key={v}>{v} минут</option>)}</select></label><button className="save-profile" onClick={save} disabled={saving}>{saving?"Сақталуда...":"Өзгерістерді сақтау"}</button></section>
      <aside className="profile-side"><h2>Бүгінгі мақсат</h2><div className="daily-ring" style={{"--daily":`${goalPercent*3.6}deg`} as React.CSSProperties}><b>{goalPercent}%</b></div><p>{Math.round(todaySeconds/60)} / {goal} минут орындалды</p><div className="account-mini-stats"><div><b>{best}</b><small>рекорд</small></div><div><b>{avg}%</b><small>дәлдік</small></div><div><b>{completedCount}</b><small>сабақ</small></div></div></aside></div>
      :<SchoolPanel profile={profile} onProfile={onProfile} onBecomeTeacher={becomeTeacher} onLesson={onLesson}/>} </section>;
}

function SchoolPanel({profile,onProfile,onBecomeTeacher,onLesson}:{profile:CloudProfile;onProfile:(p:CloudProfile)=>void;onBecomeTeacher:()=>void;onLesson:(id:number)=>void}){
  const [classes,setClasses]=useState<SchoolClass[]>([]),[selected,setSelected]=useState(""),[className,setClassName]=useState(""),[joinCode,setJoinCode]=useState(""),[assignments,setAssignments]=useState<Assignment[]>([]),[members,setMembers]=useState<Array<{user_id:string;full_name:string;avg:number;best:number}>>([]),[assignmentTitle,setAssignmentTitle]=useState(""),[lessonId,setLessonId]=useState(1),[message,setMessage]=useState("");
  const loadClasses=async()=>{if(!supabase)return;if(profile.role==="teacher"){const {data}=await supabase.from("classes").select("*").order("created_at");setClasses((data||[]) as SchoolClass[])}else{const {data}=await supabase.from("class_members").select("class_id, classes(id,name,join_code,teacher_id)");setClasses((data||[]).flatMap((row:any)=>row.classes?[row.classes]:[]) as SchoolClass[])}};
  useEffect(()=>{void loadClasses()},[profile.role]);
  useEffect(()=>{if(!selected||!supabase)return;(async()=>{const {data:a}=await supabase.from("assignments").select("id,title,lesson_id,due_at").eq("class_id",selected).order("created_at",{ascending:false});setAssignments((a||[]) as Assignment[]);if(profile.role==="teacher"){const {data:m}=await supabase.from("class_members").select("user_id, profiles(full_name)").eq("class_id",selected);const ids=(m||[]).map((x:any)=>x.user_id);const {data:r}=ids.length?await supabase.from("results").select("user_id,cpm,accuracy").in("user_id",ids):{data:[] as any[]};setMembers((m||[]).map((x:any)=>{const mine=(r||[]).filter((q:any)=>q.user_id===x.user_id);return{user_id:x.user_id,full_name:x.profiles?.full_name||"Оқушы",avg:mine.length?Math.round(mine.reduce((s:number,q:any)=>s+q.accuracy,0)/mine.length):0,best:mine.length?Math.max(...mine.map((q:any)=>q.cpm)):0}}))}})()},[selected,profile.role]);
  const createClass=async()=>{if(!supabase||!className.trim())return;const {error}=await supabase.from("classes").insert({name:className,teacher_id:profile.id});if(error)setMessage(error.message);else{setClassName("");setMessage("Сынып құрылды");void loadClasses()}};
  const join=async()=>{if(!supabase)return;const {error}=await supabase.rpc("join_class",{invite_code:joinCode});if(error)setMessage(error.message);else{setJoinCode("");setMessage("Сыныпқа қосылдыңыз");void loadClasses()}};
  const assign=async()=>{if(!supabase||!selected||!assignmentTitle.trim())return;const {error}=await supabase.from("assignments").insert({class_id:selected,teacher_id:profile.id,title:assignmentTitle,lesson_id:lessonId});if(error)setMessage(error.message);else{setAssignmentTitle("");setMessage("Тапсырма берілді");const {data}=await supabase.from("assignments").select("id,title,lesson_id,due_at").eq("class_id",selected).order("created_at",{ascending:false});setAssignments((data||[]) as Assignment[])}};
  if(profile.role!=="teacher"&&!classes.length)return <div className="school-empty"><span>♟</span><h2>Сыныпқа қосылыңыз</h2><p>Мұғалім берген алты таңбалы кодты енгізіңіз.</p><div><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} maxLength={6} placeholder="ABC123"/><button onClick={join}>Қосылу</button></div>{message&&<small>{message}</small>}<button className="teacher-switch" onClick={onBecomeTeacher}>Мен мұғаліммін →</button></div>;
  return <div className="school-layout"><aside className="class-sidebar"><h3>{profile.role==="teacher"?"Менің сыныптарым":"Менің сыныбым"}</h3>{classes.map(c=><button className={selected===c.id?"selected":""} onClick={()=>setSelected(c.id)} key={c.id}><b>{c.name}</b><small>Код: {c.join_code}</small></button>)}{profile.role==="teacher"?<div className="new-class"><input value={className} onChange={e=>setClassName(e.target.value)} placeholder="Жаңа сынып атауы"/><button onClick={createClass}>+ Құру</button></div>:<div className="new-class"><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="Қосылу коды"/><button onClick={join}>Қосылу</button></div>}{message&&<p>{message}</p>}</aside>
    <section className="class-content">{!selected?<div className="select-class">← Жұмыс істеу үшін сыныпты таңдаңыз</div>:<>{profile.role==="teacher"&&<div className="assign-form"><h2>Жаңа тапсырма</h2><input value={assignmentTitle} onChange={e=>setAssignmentTitle(e.target.value)} placeholder="Мысалы: Қазақ әріптерін қайталау"/><select value={lessonId} onChange={e=>setLessonId(Number(e.target.value))}>{Array.from({length:20},(_,i)=><option value={i+1} key={i}>Сабақ {i+1}</option>)}</select><button onClick={assign}>Тапсырма беру</button></div>}
      <div className="class-columns"><section><h2>Тапсырмалар</h2>{assignments.length?assignments.map(a=><article className="assignment" key={a.id}><span>Сабақ {a.lesson_id}</span><b>{a.title}</b>{profile.role==="student"&&<button onClick={()=>onLesson(a.lesson_id)}>Бастау →</button>}</article>):<p className="muted">Тапсырма әзірге жоқ.</p>}</section>{profile.role==="teacher"&&<section><h2>Оқушылар</h2>{members.length?members.map(m=><article className="student-row" key={m.user_id}><i>{m.full_name[0]}</i><b>{m.full_name}</b><span>{m.best} таң/мин</span><em>{m.avg}%</em></article>):<p className="muted">Оқушылар код арқылы қосылғанда осында көрінеді.</p>}</section>}</div></>}</section></div>;
}
